import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";
import GreyLine from "../components/GreyLine";
// import fs from "fs";
// import path from "path";
// import matter from "gray-matter";

export default function Home({ posts }) {
  return (
    <div className="tracking-tight font-inter text-sm text-neutral-400 min-h-screen h-full bg-neutral-900 selection:bg-neutral-300">
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative h-full min-h-screen pt-8 max-w-[36rem] m-auto">
        <Header />
        <main className="mt-16">
          <div className=" text-neutral-300">
            <p className="font-bold pb-4">About</p>
            <div className="font-normal">
              <p className="pb-4">
                Hello! I&apos;m Eemeli, a second year student at{" "}
                <a
                  href="https://www.pori.fi/kasvatus-ja-koulutus/lukio/porin-lukio"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-neutral-400 transition-all duration-200 hover:decoration-neutral-200"
                >
                  Porin Lukio
                </a>
                .
              </p>
              <p className="pb-4">
                Alongside my studies I like enjoy tinkering around with graphic
                design. You can find some of my work at the{" "}
                <Link href="/portfolio">
                  <a className="underline decoration-neutral-400 transition-all duration-200 hover:decoration-neutral-200">
                    portfolio
                  </a>
                </Link>{" "}
                section.
              </p>
              <p className="pb-4">
                I also enjoy playing around with web design! Some of my projects
                are{" "}
                <a
                  href="https://MEK-JS.vercel.app"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-neutral-400 transition-all duration-200 hover:decoration-neutral-200"
                >
                  MEK-JS
                </a>
                ,{" "}
                <a
                  href="https://porinlukio.fi"
                  target="_blank"
                  rel="noreferrer"
                  className="underline decoration-neutral-400 transition-all duration-200 hover:decoration-neutral-200"
                >
                  porinlukio.fi
                </a>{" "}
                and this very site!
              </p>
              <p className="pb-4">
                If you&apos;d like to get in touch you can find ways to contact
                me{" "}
                <Link href="/contact">
                  <a className="underline decoration-neutral-400 transition-all duration-200 hover:decoration-neutral-200">
                    here
                  </a>
                </Link>
                !
              </p>
              <img
                className="h-8"
                src="https://emojicdn.elk.sh/%E2%9C%A8?style=apple"
              />
            </div>
          </div>
        </main>
      </div>
      <GreyLine />
      <Footer />
    </div>
  );
}

// https://www.youtube.com/watch?v=MrjeefD8sac

{
  /* <p className="font-bold pb-8">Writings</p>;
{
  posts.map((post, index) => <Post post={post} />);
} */
}

// export async function getStaticProps() {
//   const files = fs.readdirSync(path.join("posts"));

//   const posts = files.map((filename) => {
//     const slug = filename.replace("md", "");

//     const markdownWithMeta = fs.readFileSync(
//       path.join("posts", filename),
//       "utf-8"
//     );

//     const { data: frontmatter } = matter(markdownWithMeta);

//     return {
//       slug,
//       frontmatter,
//     };
//   });

//   return {
//     props: {
//       posts,
//     },
//   };
// }
