import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Post from "../components/Post";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className="tracking-tight font-inter text-sm text-neutral-200 min-h-screen h-full bg-neutral-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-8 max-w-[48rem] m-auto">
        <Header />
        <main className="mt-16">
          <div className="text-base">
            <p className="font-bold">Writings</p>
            {posts.map((post, index) => (
              <Post post={post} />
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}

// https://www.youtube.com/watch?v=MrjeefD8sac

export async function getStaticProps() {
  const files = fs.readdirSync(path.join("posts"));

  const posts = files.map((filename) => {
    const slug = filename.replace("md", "");

    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );

    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}
